---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    app.kubernetes.io/name: grafana
    environment: dev
  name: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  type: ClusterIP
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: grafana
    environment: dev
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: grafana
        environment: dev
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
#            - name: GF_SECURITY_ADMIN_USER
#              value: "root"
#            - name: GF_SECURITY_ADMIN_PASSWORD
#              value: "secret"
          ports:
            - name: grafana
              protocol: TCP
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: prometheus-datasource
              readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: prometheus-datasource
          configMap:
            defaultMode: 420
            name: prometheus-datasource
