apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "id": 1,
                "orgId": 1,
                "name": "Prometheus",
                "type": "prometheus",
                "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
                "access": "proxy",
                "url": "http://prometheus-operated.monitoring.svc.cluster.local:9090",
                "password": "",
                "user": "",
                "database": "",
                "basicAuth": false,
                "isDefault": true,
                "jsonData": {
                  "timeInterval": "5s",
                  "tlsSkipVerify": true
                },
                "readOnly": false
            }
        ]
    }
