apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    environment: dev
    app.kubernetes.io/monitoring: prometheus
spec:
  selector:
    matchLabels: {}
  endpoints:
    - port: web
    - port: http
