{
 "title": "SmallRye MicroProfile Metrics",
 "description": "Visualize all MicroProfile Metrics for your MicroProfile application",
 "tags": [
  "java",
  "microprofile",
  "smallrye"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(base_thread_count, env)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(base_thread_count{env=\"$env\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(base_thread_count{env=\"$env\",job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "MicroProfile App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "com.nerdyjokes.NerdyJokeResource.average_request",
   "type": "graph",
   "description": "Average duration of request",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_nerdyjokes_NerdyJokeResource_average_request_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} q={{quantile}}/"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "How many requests have been processed",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_nerdyjokes_NerdyJokeResource_number_of_requests_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "com.nerdyjokes.NerdyJokeResource.requests",
   "type": "graph",
   "description": "Rate of requests",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_nerdyjokes_NerdyJokeResource_requests_rate_per_second{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  { "title": "MicroProfile Vendor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Committed Non Heap Memory",
   "type": "graph",
   "description": "Displays the amount of non heap memory in bytes that is committed for the Java virtual machine to use.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_committedNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Max Non Heap Memory",
   "type": "graph",
   "description": "Displays the maximum amount of used non-heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_maxNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Used Non Heap Memory",
   "type": "graph",
   "description": "Displays the amount of used non-heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_usedNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  { "title": "MicroProfile Base Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current Loaded Class Count",
   "type": "stat",
   "description": "Displays the number of classes that are currently loaded in the Java virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total Loaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes that have been loaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total Unloaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes unloaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Available Processors",
   "type": "stat",
   "description": "Displays the number of processors available to the Java virtual machine. This value may change during a particular invocation of the virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "stat",
   "description": "Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "description": "Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The Java virtual machine implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_total_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "description": "Displays the time from the start of the Java virtual machine in milliseconds.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Committed Heap Memory",
   "type": "graph",
   "description": "Displays the amount of memory in bytes that is committed for the Java virtual machine to use. This amount of memory is guaranteed for the Java virtual machine to use.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Max Heap Memory",
   "type": "graph",
   "description": "Displays the maximum amount of heap memory in bytes that can be used for memory management. This attribute displays -1 if the maximum heap memory size is undefined. This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Used Heap Memory",
   "type": "graph",
   "description": "Displays the amount of used heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "description": "Displays the current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_thread_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "description": "Displays the current number of live daemon threads.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_thread_daemon_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Peak Thread Count",
   "type": "stat",
   "description": "Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_thread_max_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  }
 ]
}